server:
  port: 8001
  servlet:
    context-path: /greeting
spring:
  application:
    name: greeting
  config:
    import: "optional:config-server:"
eureka:
  client:
    healthcheck:
      enabled: true