spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      routes:
        - id: greeting
          uri: http://127.0.0.1:8001/
          predicates:
            - Path=/greeting/**
management:
  endpoint:
    gateway:
      enabled: true # default: true
  endpoints:
    web:
      exposure:
        include: gateway
server:
  port: 8080